version: "3.8"
# docker-compose up -d
# docker exec -it mongo1 sh -c "mongo --port 30001"
# docker exec -it mongo2 sh -c "mongo --port 30002"
# docker exec -it mongo3 sh -c "mongo --port 30003"

services:
  mongo1:
    image: mongo:4.4.2
    container_name: mongo1
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30001"]
    volumes:
      #- ./scripts/mongodb_schema.js:/docker-entrypoint-initdb.d/1-init.js:ro
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data/mongo-1:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=admin
    ports:
      - 30001:30001
    networks:
      - mongo_db_network
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'my-replica-set',members:[{_id:0,host:\"mongo1:30001\"},{_id:1,host:\"mongo2:30002\"},{_id:2,host:\"mongo3:30003\"}]}).ok || rs.status().ok" | mongo --port 30001 --quiet) -eq 1
      interval: 10s
      start_period: 30s

  mongo2:
    image: mongo:4.4.2
    container_name: mongo2
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30002"]
    volumes:
      - ./data/mongo-2:/data/db
    restart: always
    ports:
      - 30002:30002
    networks:
      - mongo_db_network

  mongo3:
    image: mongo:4.4.2
    container_name: mongo3
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30003"]
    volumes:
      - ./data/mongo-3:/data/db
    ports:
      - 30003:30003
    networks:
      - mongo_db_network
    
  mongo-express:
    image: "mongo-express:latest"
    container_name: "mongo-express"
    ports:
      - 8888:8081
    networks:
      - mongo_db_network
    depends_on: 
      - "mongo1"
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=default
      - ME_CONFIG_MONGODB_SERVER=mongo1,mongo2,mongo3
      #- ME_CONFIG_MONGODB_PORT=30001
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
      - ME_CONFIG_BASICAUTH_USERNAME=my_user
      - ME_CONFIG_BASICAUTH_PASSWORD=password123
      # - ME_CONFIG_OPTIONS_EDITORTHEME=night
      # - ME_CONFIG_REQUEST_SIZE=100kb
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    restart: always
      
#volumes:
  #mongodb_master_data:
    #driver: local
  #mongodb_arbiter_data:
    #driver: local
  #mongodb_secondary_data:
    #driver: local
    
networks:
  mongo_db_network:
