version: '2'

services:
  mongodb:
    image: docker.io/bitnami/mongodb:4.4
    ports:
      - "27017:27017"
    environment:
      #- ALLOW_EMPTY_PASSWORD=yes     
      - MONGODB_ENABLE_JOURNAL=true
      - MONGODB_SYSTEM_LOG_VERBOSITY=3
      - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=2
      # Root user with unlimited access
      - MONGODB_ROOT_USER=admin
      - MONGODB_ROOT_PASSWORD=password123
      # User with Restricted access
      - MONGODB_USERNAME=my_user
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=my_database
    volumes:
      #- ./scripts/mongodb_schema.js:/docker-entrypoint-initdb.d/1-init.js:ro
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      #- 'mongodb_data:/bitnami/mongodb'

  mongo-express:
    image: "mongo-express:latest"
    container_name: "mongo-express"
    ports:
      - 8888:8081
    links:
      - "mongodb"
    depends_on: 
      - "mongodb"
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=default
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
      - ME_CONFIG_BASICAUTH_USERNAME=my_user
      - ME_CONFIG_BASICAUTH_PASSWORD=password123
      # - ME_CONFIG_OPTIONS_EDITORTHEME=night
      # - ME_CONFIG_REQUEST_SIZE=100kb
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    restart: always
    
#volumes:
 # mongodb_data:
   # driver: local
