version: '3.3'

services:
  keycloak-postgres:
    container_name: "keycloak-postgres"
    image: postgres:${POSTGRESQL_VERSION}
    mem_limit: 250m
    hostname: keycloak-postgres
    env_file: .env
    volumes:
      - "./postgresql_scripts:/docker-entrypoint-initdb.d/"
      - "./postgresql_data:/var/lib/postgresql/data"
    restart: always   
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    networks:
      - local-keycloak

  keycloak:
    depends_on:
      - keycloak-postgres
    image: jboss/keycloak:${KEYCLOAK_VERSION}    
    mem_limit: 250m
    container_name: "keycloak-server"
    hostname: keycloak
    env_file: .env
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_SCHEMA: ${POSTGRESQL_SCHEMA}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      JAVA_OPTS: -server -Xms64m -Xmx1024m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -Dkeycloak.profile=preview
      #KEYCLOAK_LOGLEVEL: DEBUG
      #ROOT_LOGLEVEL: DEBUG
      #Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"   
    ports:
      - "28080:8080"
    restart: always
    networks:
      - local-keycloak

volumes:
  postgres_data:
      driver: local
      
networks:
  local-keycloak: