version: '3.3'

services:
  postgres:
    container_name: "keycloak-postgres"
    image: postgres:9.6.17
    env_file: .env
    volumes:
      - "./postgresql_scripts:/docker-entrypoint-initdb.d/"
      - postgres_db:/var/lib/postgresql/data
    restart: always   
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    networks:
      - local-keycloak

  keycloak:
    depends_on:
      - postgres
    container_name: "keycloak-server"
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_SCHEMA: ${POSTGRESQL_SCHEMA}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      JAVA_OPTS: -server -Xms64m -Xmx1024m -XX:MetaspaceSize=1024M -Dkeycloak.profile.feature.token_exchange=enabled
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    env_file: .env
    ports:
      - "28080:8080"
    restart: always
    networks:
      - local-keycloak

volumes:
  postgres_db:
      driver: local
      
networks:
  local-keycloak: