version: '3.8'

services: 
  postgres:
    image: postgres:16.1
    restart: always
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: postgres
    healthcheck: 
      test: "exit 0"
    ports:
      - "5432:5432"
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - keycloak-internal
  
  keycloak:
    container_name: dev_keycloak
    image: quay.io/keycloak/keycloak:23.0.3
    command: start-dev
    restart: always
    links:
      - postgres
    environment:    
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak

      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/demo/certs/localhostcert.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/demo/certs/localhostkey.pem
      KC_FEATURES: token-exchange,admin-fine-grained-authz,scripts,update-email,client-secret-rotation,impersonation
    ports:
      - "8843:8443"
      - "9082:8080"
    volumes:
      - ./certs:/opt/keycloak/demo/certs
    networks:
      - keycloak-internal
    depends_on:
      keycloak_db:
        condition: service_healthy
      
volumes: 
  pgdata_keycloak_data:
  
networks:
  keycloak-internal:
    driver: bridge