version: '3.7'

services:    
  mongodb:
    build:
      context: mongodb
      dockerfile: Dockerfile
    image: "mongo:${MONGO_VERSION}"
    mem_limit: 300m
    container_name: ${MONGO_CONTAINER_NAME}
    restart: always
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongo-data:/data/db
     #- ./scripts/mongodb_schema.js:/docker-entrypoint-initdb.d/1-init.js:ro
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    networks:
      - backend
  
  mongo-express:
    image: mongo-express
    mem_limit: 300m
    container_name: ${MONGOEXPRESS_CONTAINER_NAME}
    restart: always
    env_file: .env
    ports:
      - "8888:8081"
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=default
      - ME_CONFIG_MONGODB_SERVER=${MONGO_CONTAINER_NAME}
      - ME_CONFIG_MONGODB_PORT=${MONGO_DB_PORT}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - backend
      
networks:
  backend:
    driver: bridge

volumes:
  mongo-data:
  
  
  