version: '3.3'

services:
  keycloak-postgresql:
    container_name: "keycloak-postgresql"
    image: postgres:${POSTGRESQL_VERSION}
    env_file: .env
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: always   
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    networks:
      - local-keycloak

  keycloak:
    depends_on:
      - keycloak-postgresql
    container_name: "keycloak"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgresql
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_SCHEMA: ${POSTGRESQL_SCHEMA}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      JAVA_OPTS: -server -Xms64m -Xmx1024m -XX:MetaspaceSize=1024M -Dkeycloak.profile.feature.token_exchange=enabled -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled -Dkeycloak.profile.feature.impersonation=enabled
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    env_file: .env
    ports:
      - "8190:8080"
    restart: always
    networks:
      - local-keycloak

volumes:
  postgresql_data:
      driver: local
      
networks:
  local-keycloak: